### ISSUE TITLE
Some qusetion about using flexfringe (When I qoute your works )

### ISSUE THREAD

**Issue by richao-hu** [laxris/flexfringe-colab#1]
When I run the command line"./start.sh batch-mealy.ini ../data/original/traces10000.txt" in my nain directery,it show the question:
welcome, running git commit c8fad5bd3b0c0dad0e28ec7606f20a7fcf975071 with: ./flexfringe --heuristic-name mealy --data-name mealy_data --sinkson 0 --state_count 15 --symbol_count 5 --satdfabound 2000 --largestblue 1 --lowerbound 10 --extend 0 --debug 1 ../data/original/traces10000.txt 
valid: mealy
aic 1
alergia 1
alergia94 1
conflict_driven 1
conflict_edsm_driven 1
conflict_overlap_driven 1
count_driven 1
depth_driven 1
evidence_driven 1
fixed_depth_mse_error 1
full_overlap_driven 1
kldistance 1
likelihoodratio 1
mealy 1
mse_error 1
overlap4logs 1
overlap_driven 1
process_mining 1
Using heuristic mealy
Creating apta using evaluation class mealy_data
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
./start.sh: line 18:  2966 Aborted                 (core dumped) ./flexfringe $param $2
"
But I don't know what wrong with the code ,Therefore, I hereby ask for your help, and I would appreciate it if you could reply to me!

**Comment by laxris** [comment]
Hi, thanks for reaching out. At the moment, flexfringe does not gracefully handle errors. What is happening here is that the input file got moved, and flexfringe tries to read and process from the invalid file handle.
The data file is now
> ./data/original/traces1000.txt
so if you run
./start.sh batch-mealy.ini ./data/original/traces1000.txt   
it should just run smoothly. Let me know if you run in any more problems, we're very interested in making it more user friendly and improving the documentation.

**Comment by richao-hu** [comment]
Oh!I'm really sorry that I misread the file name. Thank you very much for your reminding!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chris Hammerschmidt"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 晚上9:40
收件人:&nbsp;"laxris/flexfringe-colab"<flexfringe-colab@noreply.github.com&gt;;
抄送:&nbsp;"暑夏、殇的园"<1213648630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [laxris/flexfringe-colab] Some qusetion about using flexfringe (When I qoute your works ) (#1)





 
Hi, thanks for reaching out. At the moment, flexfringe does not gracefully handle errors. What is happening here is that the input file got moved, and flexfringe tries to read and process from the invalid file handle.
 The data file is now
  
./data/original/traces1000.txt
 so if you run
 ./start.sh batch-mealy.ini ./data/original/traces1000.txt
 it should just run smoothly. Let me know if you run in any more problems, we're very interested in making it more user friendly and improving the documentation.

**Comment by laxris** [comment]
No problem, feel free to open another issue if you run into more problems. We recently got a scientific programmer to help out making everything more straightforward and user-friendly.
